# docker compose config for development environments
version: "3"
services:
  propeller-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - SQL_SAFE_UPDATES=1
    image: mysql:8
    ports:
      - 0.0.0.0:3306:3306
